# Adding and Removing Rows and Columns in Pandas

## Objective
This notebook demonstrates how to modify DataFrame structure by adding and removing rows and columns using vectorized operations and built-in pandas methods.

In [1]:
people = {
    "first": ["Kenan", "Sercem" , "Ahmet", "Huseyin"],
    "last": ["KURT" , "MAKUM" , "AYCAN", "KURT"],
    "email":["kt@gmail.com", "sm@gmail.com" , "aa@gmail.com", "hd@gmail.com"]
}

import pandas as pd
df = pd.DataFrame(people)
df

     first   last         email
0    Kenan   KURT  kt@gmail.com
1   Sercem  MAKUM  sm@gmail.com
2    Ahmet  AYCAN  aa@gmail.com
3  Huseyin   KURT  hd@gmail.com

In [2]:
df['first'] + ' ' + df['last']

0      Kenan KURT
1    Sercem MAKUM
2     Ahmet AYCAN
3    Huseyin KURT
dtype: str

In [3]:
df['full_name'] = df['first'] + ' ' + df['last']
df

     first   last         email     full_name
0    Kenan   KURT  kt@gmail.com    Kenan KURT
1   Sercem  MAKUM  sm@gmail.com  Sercem MAKUM
2    Ahmet  AYCAN  aa@gmail.com   Ahmet AYCAN
3  Huseyin   KURT  hd@gmail.com  Huseyin KURT

In [4]:
df.drop(columns=['first','last'], inplace = True)

In [5]:
df

          email     full_name
0  kt@gmail.com    Kenan KURT
1  sm@gmail.com  Sercem MAKUM
2  aa@gmail.com   Ahmet AYCAN
3  hd@gmail.com  Huseyin KURT

In [6]:
df['full_name'].str.split(' ', expand = True)

         0      1
0    Kenan   KURT
1   Sercem  MAKUM
2    Ahmet  AYCAN
3  Huseyin   KURT

In [7]:
df[['first', 'last']] = df['full_name'].str.split(' ', expand = True)
df

          email     full_name    first   last
0  kt@gmail.com    Kenan KURT    Kenan   KURT
1  sm@gmail.com  Sercem MAKUM   Sercem  MAKUM
2  aa@gmail.com   Ahmet AYCAN    Ahmet  AYCAN
3  hd@gmail.com  Huseyin KURT  Huseyin   KURT

In [8]:
df.drop(index = 3)

          email     full_name   first   last
0  kt@gmail.com    Kenan KURT   Kenan   KURT
1  sm@gmail.com  Sercem MAKUM  Sercem  MAKUM
2  aa@gmail.com   Ahmet AYCAN   Ahmet  AYCAN

In [9]:
df

          email     full_name    first   last
0  kt@gmail.com    Kenan KURT    Kenan   KURT
1  sm@gmail.com  Sercem MAKUM   Sercem  MAKUM
2  aa@gmail.com   Ahmet AYCAN    Ahmet  AYCAN
3  hd@gmail.com  Huseyin KURT  Huseyin   KURT

In [10]:
df.drop(index = df[df['last'] == 'KURT'].index)

          email     full_name   first   last
1  sm@gmail.com  Sercem MAKUM  Sercem  MAKUM
2  aa@gmail.com   Ahmet AYCAN   Ahmet  AYCAN

In [11]:
people = {
    "first": ["Kenan", "Sercem" , "Ahmet", "Huseyin"],
    "last": ["KURT" , "MAKUM" , "AYCAN", "KURT"],
    "email":["kt@gmail.com", "sm@gmail.com" , "aa@gmail.com", "hd@gmail.com"]
}

import pandas as pd
df = pd.DataFrame(people)
df

     first   last         email
0    Kenan   KURT  kt@gmail.com
1   Sercem  MAKUM  sm@gmail.com
2    Ahmet  AYCAN  aa@gmail.com
3  Huseyin   KURT  hd@gmail.com

In [12]:
df = df[df['last'] != 'KURT']
df

    first   last         email
1  Sercem  MAKUM  sm@gmail.com
2   Ahmet  AYCAN  aa@gmail.com